export const characters = [
    { id: 1, name: "001 户山香澄", category: ["Poppin'Party"] },
    { id: 2, name: "002 花园多惠", category: ["Poppin'Party"] },
    { id: 3, name: "003 牛込里美", category: ["Poppin'Party"] },
    { id: 4, name: "004 山吹沙绫", category: ["Poppin'Party"] },
    { id: 5, name: "005 市谷有咲", category: ["Poppin'Party"] },
    { id: 6, name: "006 美竹兰", category: ["Afterglow"] },
    { id: 7, name: "007 青叶摩卡", category: ["Afterglow"] },
    { id: 8, name: "008 上原绯玛丽", category: ["Afterglow"] },
    { id: 9, name: "009 宇田川巴", category: ["Afterglow"] },
    { id: 10, name: "010 羽泽鸫", category: ["Afterglow"] },
    { id: 11, name: "011 弦卷心", category: ["Hello, Happy World!"] },
    { id: 12, name: "012 濑田薰", category: ["Hello, Happy World!"] },
    { id: 13, name: "013 北泽育美", category: ["Hello, Happy World!"] },
    { id: 14, name: "014 松原花音", category: ["Hello, Happy World!"] },
    { id: 15, name: "015 米歇尔", category: ["Hello, Happy World!", "非人类"] },
    { id: 16, name: "016 丸山彩", category: ["Pastel*Palettes"] },
    { id: 17, name: "017 冰川日菜", category: ["Pastel*Palettes"] },
    { id: 18, name: "018 白鹭千圣", category: ["Pastel*Palettes"] },
    { id: 19, name: "019 大和麻弥", category: ["Pastel*Palettes"] },
    { id: 20, name: "020 若宫伊芙", category: ["Pastel*Palettes"] },
    { id: 21, name: "021 凑友希那", category: ["Roselia"] },
    { id: 22, name: "022 冰川纱夜", category: ["Roselia"] },
    { id: 23, name: "023 今井莉莎", category: ["Roselia"] },
    { id: 24, name: "024 宇田川亚子", category: ["Roselia"] },
    { id: 25, name: "025 白金燐子", category: ["Roselia"] },
    { id: 26, name: "026 仓田真白", category: ["Morfonica"] },
    { id: 27, name: "027 桐谷透子", category: ["Morfonica"] },
    { id: 28, name: "028 广町七深", category: ["Morfonica"] },
    { id: 29, name: "029 二叶筑紫", category: ["Morfonica"] },
    { id: 30, name: "030 八潮瑠唯", category: ["Morfonica"] },
    { id: 31, name: "031 LAYER", category: ["RAISE A SUILEN"] },
    { id: 32, name: "032 LOCK", category: ["RAISE A SUILEN"] },
    { id: 33, name: "033 MASKING", category: ["RAISE A SUILEN"] },
    { id: 34, name: "034 PAREO", category: ["RAISE A SUILEN"] },
    { id: 35, name: "035 CHU²", category: ["RAISE A SUILEN"] },
    { id: 36, name: "036 高松灯", category: ["MyGO!!!!!", "CRYCHIC"] },
    { id: 37, name: "037 千早爱音", category: ["MyGO!!!!!"] },
    { id: 38, name: "038 要乐奈", category: ["MyGO!!!!!"] },
    { id: 39, name: "039 长崎爽世", category: ["MyGO!!!!!", "CRYCHIC"] },
    { id: 40, name: "040 椎名立希", category: ["MyGO!!!!!", "CRYCHIC"] },
    { id: 201, name: "201 月岛麻里奈", category: ["工作人员"] },
    // { id: 202, name: "202 快餐店店员", category: ["工作人员"] },
    // { id: 203, name: "203 杂货店店员", category: ["工作人员"] },
    // { id: 204, name: "204 书店店员", category: ["工作人员"] },
    // { id: 205, name: "205 咖啡厅店员", category: ["工作人员"] },
    // { id: 207, name: "207 市谷万实", category: ["家人朋友"] },
    // { id: 208, name: "208 乐曲店店员", category: ["工作人员"] },
    { id: 209, name: "209 灯里", category: ["家人朋友"] },
    { id: 210, name: "210 兰的父亲", category: ["家人朋友", "男性"] },
    { id: 211, name: "211 黑衣", category: ["家人朋友"] },
    { id: 212, name: "212 友希那的父亲", category: ["家人朋友", "男性"] },
    { id: 213, name: "213 步美", category: ["Marmalade"] },
    { id: 214, name: "214 户山明日香", category: ["家人朋友"] },
    { id: 215, name: "215 都筑诗船", category: ["工作人员", "家人朋友"] },
    { id: 216, name: "216 二十骑雏子", category: ["Glitter*Green"] },
    { id: 217, name: "217 玛丽·安德罗美亚", category: ["非人类"] },
    { id: 218, name: "218 芹泽澪", category: ["ViVidCanvas"] },
    { id: 219, name: "219 山濑濑理奈", category: ["ViVidCanvas"] },
    { id: 220, name: "220 小金井志乃", category: ["ViVidCanvas"] },
    { id: 221, name: "221 巽幸太郎", category: ["男性", "其他"] },
    { id: 222, name: "222 晴海", category: ["家人朋友"] },
    // { id: 223, name: "223 圣诞节路人店员1", category: ["工作人员"] },
    // { id: 224, name: "224 圣诞节路人店员2", category: ["工作人员"] },
    { id: 225, name: "225 真次凛凛子", category: ["工作人员"] },
    { id: 226, name: "226 东中野奈绪", category: ["Marmalade"] },
    { id: 227, name: "227 月之森理事长", category: ["其他"] },
    { id: 228, name: "228 夏洛特·露易丝·三园", category: ["家人朋友"] },
    { id: 229, name: "229 纯田真奈", category: ["Sumimi"] },
    { id: 301, name: "301 鹈泽莉依", category: ["Glitter*Green"] },
    { id: 302, name: "302 牛込百合", category: ["Glitter*Green", "家人朋友"] },
    { id: 303, name: "303 Hanne", category: ["家人朋友"] },
    { id: 304, name: "304 海野夏希", category: ["CHiSPA"] },
    { id: 305, name: "305 企鹅", category: ["非人类"] },
    { id: 307, name: "307 户山香澄（幼年）", category: ["幼年"] },
    { id: 308, name: "308 北泽育美（幼年）", category: ["幼年"] },
    { id: 309, name: "309 凑友希那&白金燐子", category: ["其他"] },
    { id: 310, name: "310 美竹兰（幼年）", category: ["幼年"] },
    { id: 311, name: "311 青叶摩卡（幼年）", category: ["幼年"] },
    { id: 312, name: "312 上原绯玛丽（幼年）", category: ["幼年"] },
    { id: 313, name: "313 宇田川巴（幼年）", category: ["幼年"] },
    { id: 314, name: "314 羽泽鸫（幼年）", category: ["幼年"] },
    { id: 315, name: "315 白金燐子（幼年）", category: ["幼年"] },
    { id: 316, name: "316 小咕咕", category: ["非人类"] },
    { id: 317, name: "317 朝日六花（路人）", category: ["其他"] },
    { id: 318, name: "318 凑友希那（幼年）", category: ["幼年"] },
    { id: 319, name: "319 今井莉莎（幼年）", category: ["幼年"] },
    { id: 320, name: "320 白鹭千圣（幼年）", category: ["幼年"] },
    { id: 321, name: "321 濑田薰（幼年）", category: ["幼年"] },
    { id: 322, name: "322 仓田真白（路人）", category: ["其他"] },
    { id: 323, name: "323 桐谷透子（路人）", category: ["其他"] },
    { id: 326, name: "326 冰川纱夜（幼年）", category: ["幼年"] },
    { id: 327, name: "327 冰川日菜（幼年）", category: ["幼年"] },
    { id: 328, name: "328 妮可莉娜", category: ["其他"] },
    { id: 329, name: "329 另一个里美", category: ["其他"] },
    { id: 330, name: "330 花园多惠（幼年）", category: ["幼年"] },
    { id: 331, name: "331 LAYER（幼年）", category: ["幼年"] },
    { id: 332, name: "332 市谷有咲（幼年）", category: ["幼年"] },
    { id: 333, name: "333 CHU²（幼年）", category: ["幼年"] },
    { id: 334, name: "334 八潮瑠唯（幼年）", category: ["幼年"] },
    { id: 335, name: "335 真白史莱姆", category: ["非人类"] },
    { id: 336, name: "336 哥布林", category: ["非人类"] },
    { id: 337, name: "337 三角初华", category: ["Ave Mujica", "Sumimi"] },
    { id: 338, name: "338 若叶睦", category: ["Ave Mujica", "CRYCHIC"] },
    { id: 339, name: "339 八幡海铃", category: ["Ave Mujica"] },
    { id: 340, name: "340 祐天寺若麦", category: ["Ave Mujica"] },
    { id: 341, name: "341 丰川祥子", category: ["Ave Mujica", "CRYCHIC"] },
    { id: 342, name: "342 宇田川亚子（幼年）", category: ["幼年"] },
    { id: 343, name: "343 要乐奈（幼年）", category: ["幼年"] },
    { id: 344, name: "344 若叶睦？", category: ["其他"] },
    { id: 345, name: "345 若叶睦？", category: ["其他"] },
    { id: 346, name: "346 Hello Kitty", category: ["非人类"] },
    { id: 347, name: "347 布丁狗", category: ["非人类"] },
    { id: 348, name: "348 帕恰狗", category: ["非人类"] },
    { id: 349, name: "349 酷企鹅", category: ["非人类"] },
    { id: 350, name: "350 蛋黄哥", category: ["非人类"] },
    { id: 351, name: "351 大耳狗", category: ["非人类"] },
    { id: 352, name: "352 美乐蒂", category: ["非人类"] },
    { id: 353, name: "353 酷洛米", category: ["非人类"] },
    { id: 354, name: "354 山姆企鹅", category: ["非人类"] },
    { id: 355, name: "355 大眼蛙", category: ["非人类"] },
    { id: 501, name: "501 MASKING&PAREO", category: ["其他"] },
    { id: 502, name: "502 宇田川亚子&白金燐子&LOCK", category: ["其他"] },
    { id: 601, name: "601 奥泽美咲", category: ["其他"] },
    { id: 999, name: "999 备用", category: ["其他"] },
];

export function queryCharacters({ page = 1, limit = 50, category = null }) {
    const safePage = Number.isFinite(page) && page > 0 ? page : 1;
    const safeLimit = Number.isFinite(limit) && limit > 0 ? limit : 50;

    let filteredCharacters = characters;
    if (category) {
        filteredCharacters = characters.filter((char) => char.category.includes(category));
    }

    const startIndex = (safePage - 1) * safeLimit;
    const endIndex = startIndex + safeLimit;
    const paginatedCharacters = filteredCharacters.slice(startIndex, endIndex);

    return {
        characters: paginatedCharacters,
        pagination: {
            page: safePage,
            limit: safeLimit,
            total: filteredCharacters.length,
            totalPages: Math.ceil(filteredCharacters.length / safeLimit),
            hasNext: endIndex < filteredCharacters.length,
            hasPrev: safePage > 1,
        },
    };
}
