export const EXTERNAL_URLS = {
  bangdreamR2Origin: "https://bangdreamr2.haneoka.org",
  bestdoriSupport: "https://bestdori.com/home/support",
  bestdoriLive2DAssetBase: "https://bestdori.com/tool/live2d/asset",
  sevenZipWasmCdn: "https://cdn.jsdelivr.net/npm/7z-wasm@1.2.0/7zz.wasm",
};

export const PUBLIC_ASSET_PATHS = {
  libarchiveScript: "/libarchive.js",
  libarchiveWasm: "/libarchive.wasm",
  sevenZipScript: "/7zz.umd.js",
  sevenZipWasm: "/7zz.wasm",
  live2dScripts: ["/live2d.min.js", "/live2dcubismcore.min.js"],
  modelMaskTexture: "../../chara/000_general/texture_00.png",
};

export const API_ROUTES = {
  models: "/api/models",
  download: "/api/download",
  downloadInfo: "/api/download-info",
  chara: "/api/chara",
  charaModified: "/api/charam",
};

export const ZIP_METADATA = {
  comment: "Generated by live2d.haneoka.org",
};

export function getLive2DBranch(isModified) {
  return isModified ? "live2d-modified" : "live2d";
}

export function getLive2DBaseUrl({ isModified, model }) {
  return `${EXTERNAL_URLS.bangdreamR2Origin}/${getLive2DBranch(isModified)}/chara/${model}_rip/`;
}

export function getLive2DModelIndexUrl(isModified) {
  return `${EXTERNAL_URLS.bangdreamR2Origin}/${getLive2DBranch(isModified)}/_info.json`;
}

export function getViewerModelApiBase(modelId, isModified) {
  const apiPrefix = isModified ? API_ROUTES.charaModified : API_ROUTES.chara;
  return `${apiPrefix}/${modelId}/`;
}

export function getModelsApiUrl(characterId, isModified) {
  const params = new URLSearchParams({
    characterId,
    isModified: String(Boolean(isModified)),
  });
  return `${API_ROUTES.models}?${params.toString()}`;
}

export function getDownloadApiUrl(modelId, isModified) {
  const params = new URLSearchParams({
    isModified: String(Boolean(isModified)),
  });
  return `${API_ROUTES.download}/${encodeURIComponent(modelId)}?${params.toString()}`;
}

export function getDownloadInfoApiUrl(modelId, isModified) {
  const params = new URLSearchParams({
    isModified: String(Boolean(isModified)),
  });
  return `${API_ROUTES.downloadInfo}/${encodeURIComponent(modelId)}?${params.toString()}`;
}

export function getBestdoriAssetUrl(region, assetId) {
  return `${EXTERNAL_URLS.bestdoriLive2DAssetBase}/${region}/live2d/chara/${encodeURIComponent(assetId)}`;
}
