export const EXTERNAL_URLS = {
  bangdreamR2Origin: "https://bangdreamr2.haneoka.org",
  bestdoriSupport: "https://bestdori.com/home/support",
  bestdoriLive2DAssetBase: "https://bestdori.com/tool/live2d/asset",
  bangdreamSpineAssetBase: "https://bangdreamr2.haneoka.org/sdchara",
  sevenZipWasmCdn: "https://cdn.jsdelivr.net/npm/7z-wasm@1.2.0/7zz.wasm",
};

export const PUBLIC_ASSET_PATHS = {
  libarchiveScript: "/libarchive.js",
  libarchiveWasm: "/libarchive.wasm",
  sevenZipScript: "/7zz.umd.js",
  sevenZipWasm: "/7zz.wasm",
  live2dScripts: ["/live2d.min.js", "/live2dcubismcore.min.js"],
  modelMaskTexture: "../../chara/000_general/texture_00.png",
};

export const API_ROUTES = {
  models: "/api/models",
  characterAvailability: "/api/character-availability",
  spineModels: "/api/spine-models",
  download: "/api/download",
  spineDownload: "/api/spine-download",
  downloadInfo: "/api/download-info",
  spineDownloadInfo: "/api/spine-download-info",
  chara: "/api/chara",
  charaModified: "/api/charam",
  spine: "/api/spine",
};

export const ZIP_METADATA = {
  comment: "Generated by live2d.haneoka.org",
};

const MODEL_LIST_RULES_VERSION = "alias-100-v2";

export function isLive2DGeneralModel(model) {
  return typeof model === "string" && model.endsWith("_general");
}

export function getLive2DBranch(isModified, model = null) {
  if (isLive2DGeneralModel(model)) {
    return "live2d";
  }
  return isModified ? "live2d-modified" : "live2d";
}

export function getLive2DBaseUrl({ isModified, model }) {
  return `${EXTERNAL_URLS.bangdreamR2Origin}/${getLive2DBranch(isModified, model)}/chara/${model}_rip/`;
}

export function getLive2DModelIndexUrl(isModified) {
  return `${EXTERNAL_URLS.bangdreamR2Origin}/${getLive2DBranch(isModified)}/_info.json`;
}

export function getSpineModelIndexUrl() {
  return `${EXTERNAL_URLS.bangdreamSpineAssetBase}/_info.json`;
}

export function getViewerModelApiBase(modelId, isModified) {
  const apiPrefix = isModified ? API_ROUTES.charaModified : API_ROUTES.chara;
  return `${apiPrefix}/${modelId}/`;
}

export function getViewerSpineApiBase(modelId) {
  return `${API_ROUTES.spine}/${encodeURIComponent(modelId)}/`;
}

export function getModelsApiUrl(characterId, isModified) {
  const params = new URLSearchParams({
    characterId,
    isModified: String(Boolean(isModified)),
    rulesVersion: MODEL_LIST_RULES_VERSION,
  });
  return `${API_ROUTES.models}?${params.toString()}`;
}

export function getSpineModelsApiUrl(characterId) {
  const params = new URLSearchParams();
  if (characterId) {
    params.set("characterId", characterId);
  }
  params.set("rulesVersion", MODEL_LIST_RULES_VERSION);

  const query = params.toString();
  return query ? `${API_ROUTES.spineModels}?${query}` : API_ROUTES.spineModels;
}

export function getCharacterAvailabilityApiUrl(modelType, isModified = false) {
  const params = new URLSearchParams({
    modelType,
    rulesVersion: MODEL_LIST_RULES_VERSION,
  });

  if (modelType === "live2d") {
    params.set("isModified", String(Boolean(isModified)));
  }

  return `${API_ROUTES.characterAvailability}?${params.toString()}`;
}

export function getDownloadApiUrl(modelId, isModified) {
  const params = new URLSearchParams({
    isModified: String(Boolean(isModified)),
  });
  return `${API_ROUTES.download}/${encodeURIComponent(modelId)}?${params.toString()}`;
}

export function getSpineDownloadApiUrl(modelId) {
  return `${API_ROUTES.spineDownload}/${encodeURIComponent(modelId)}`;
}

export function getDownloadInfoApiUrl(modelId, isModified) {
  const params = new URLSearchParams({
    isModified: String(Boolean(isModified)),
  });
  return `${API_ROUTES.downloadInfo}/${encodeURIComponent(modelId)}?${params.toString()}`;
}

export function getSpineDownloadInfoApiUrl(modelId) {
  return `${API_ROUTES.spineDownloadInfo}/${encodeURIComponent(modelId)}`;
}

export function getBestdoriAssetUrl(region, assetId) {
  return `${EXTERNAL_URLS.bestdoriLive2DAssetBase}/${region}/live2d/chara/${encodeURIComponent(assetId)}`;
}
